Update ssh2pem
bugfix

diff --git a/ssh2pem b/ssh2pem
--- a/ssh2pem
+++ b/ssh2pem
@@ -19,10 +19,8 @@ fi
 if [[ $(dpkg --get-selections | grep -w "haveged" | awk '{print $1}' | head -1) = haveged ]]; then
 	echo "El paquete haveged esta instalado."
 else
-	echo "ERROR: El paquete haveged no esta instalado, se procede a instalar"
-	apt update -q
-	apt -y install haveged
-	apt clean
+	echo "ERROR: El paquete haveged no esta instalado."
+	exit 1
 fi
 
 if [[ -z "$1" ]]; then
